
const {REACT_APP_GOOGLE_API_BASE_URL: GOOGLE_API_BASE_URL, REACT_APP_GOOGLE_API_KEY: GOOGLE_API_KEY, REACT_APP_PROXY: PROXY_URL} = process.env;

export const config = { api: {
        GOOGLE_API_BASE_URL, GOOGLE_API_KEY, PROXY_URL
    }};
